---
output: 
  pdf_document:
    keep_tex: true
header-includes:
  - \usepackage{float}
params:
  game_data: "07_17_2025 4_57_12 PM-KCL GroundSloths 2025@KCL BobCats 2025_CLEAN.csv"
  home_team: "Bobcats"
  away_team: "Groundsloths"
  game_date: "07/17"
  league: "KCL"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(patchwork)


here::i_am("Ump_Reports/ump_report_test.Rmd")
source(here("Ump_Reports", "ump_report.R"))


```


\begin{center}
    \Huge \textbf{Umpire Report}
\end{center}

\begin{center}
    \LARGE \textbf{`r params$away_team` @ `r params$home_team`}
\end{center}

\begin{center}
    \Large `r params$game_date`
\end{center}




```{r data import/cleaning, include=FALSE}

ifelse(params$league == "KCL", df <- read_csv(here("kclData", params$game_data)),
       df <- read_csv(here("CornBeltersData", params$game_data)))

#df <- read_csv(here("kclData", params$game_data))

calls <- classify(df)
split_calls <- splits(calls)

```


```{r accuracy plot, echo = FALSE, fig.pos ='H'}
plots <- rings(calls)
accuracy_plots <- plots$overall + plots$iz + plots$oz
accuracy_plots
```

\newpage

\begin{center}
  \LARGE \textbf{Zone Plots}
\end{center}

```{r zone plot, echo = FALSE, fig.pos ='H'}
incorrect_balls <- split_calls$iz %>%
   filter(PitchCall == 'BallCalled')
incorrect_strikes <- split_calls$oz %>%
  filter(PitchCall == "StrikeCalled")

zone_plots <- zones(incorrect_balls, incorrect_strikes)

final_plot <- zone_plots$oz_plot + zone_plots$iz_plot +
  plot_annotation(theme = theme(plot.margin = margin(0, 0, 0, 0)))

final_plot
```

